
RUN \
        dir=/tmp/pHash && \
        mkdir -p ${dir} && \
        cd ${dir} && \
        git clone https://github.com/faisyl/pHash-mirror.git&& \
        cd ./pHash-mirror && \
        cp CImg.h /opt/ffmpeg/include &&\
        export LD_LIBRARY_PATH=/opt/ffmpeg/lib && \
        aclocal && libtoolize --force && autoreconf -fiv && automake --add-missing && \
        ./configure --prefix=/usr/local CFLAGS=-I/opt/ffmpeg/include \
        	CXXFLAGS=-I/opt/ffmpeg/include LDFLAGS=-L/opt/ffmpeg/lib && \
        make  && \
        make install  && \
        rm -rf ${dir}